spring:
  application:
    name: domain-core-security-center
    version: 1.0.0
    description: Security Center - Authentication and Session Management
    team:
      name: Firefly Software Solutions Inc
      email: dev@getfirefly.io

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"